### ISSUE TITLE
Implementing custom blocks into vanilla recipes 

### ISSUE THREAD

**Issue by AsgrimS** [skylinerw/guides#13]
So, I've made a custom wood block in my mod and now I can't find any way to make it work with all vanilla recipes. Do I have to create a lot of JSON files for each of  standard items like crafting table, chest, boat, sticks etc.. or is there any better method for that?

**Comment by Hugman76** [comment]
As of 1.12, you cannot really do this. With 1.13, you could add your custom block to the `minecraft:planks `tag.

**Comment by AsgrimS** [comment]
Oh, I see. Is modding in 1.13 going to be changed a lot or it'll add just a bunch of useful commands?

**Comment by Hugman76** [comment]
In the modding way, I don't really know. But for sure, most of every objects will be renamed.

**Comment by mainrs** [comment]
It doesn't sound like you are using forge for modding anyways, so no, modding won't change a lot. The new additions are some functions and the new tags. Those tags are basically the same as forge's oredictionary entries, registering your wood under the entry "planksWood" should make it available and you should be able to craft chests, sticks etc with it.

**Comment by AsgrimS** [comment]
Thanks
