### ISSUE TITLE
There is no clear license

### ISSUE THREAD

**Issue by Levertion** [skylinerw/guides#16]
This project doesn't have a license. This makes it unclear what permissions we have for redistributing. 

I'm asking because for <https://github.com/Levertion/minecraft-json-schemas> I needed descriptions for many aspects, which I could have taken from these guides, had I been able to clearly know that I may.

Personally, I would choose a license such as the CC-BY, although more restrictive or permissive licenses are available.

**Comment by skylinerw** [comment]
Thanks for the heads-up! I'll take your advice and go with CC-BY. Just to be absolutely clear before applying it: you mean this one, yes? https://choosealicense.com/licenses/cc-by-4.0/

**Comment by Levertion** [comment]
🎉 

Yep, that should be fine. I would follow the instructions on [this page](https://creativecommons.org/choose/) personally.

**Comment by skylinerw** [comment]
✔️ Added
